apiVersion: v1
kind: Service
metadata:
  name: forum
spec:
  selector:
    app: forum
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
spec: # specification for deployment resource
  replicas: 1
  selector:
    matchLabels:
      app: forum
  template: # blueprint for pods
    metadata:
      labels:
        app: forum # service will look for this label
    spec: # specification for pods
      containers:
      - name: forum
        image: docker.io/dymurray/demo
        ports:
        - containerPort: 8080 #default one
